/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 28 20:18:01 GMT 2024
 */

package org.evoservice.RegistroDiCassa;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegistroDiCassav2_ASM_ESTest extends RegistroDiCassav2_ASM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegistroDiCassav2_ASM registroDiCassav2_ASM0 = new RegistroDiCassav2_ASM();
      assertNotNull(registroDiCassav2_ASM0);
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertNull(registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStato());
      assertNull(registroDiCassav2_ASM0.getAggiungiPizza());
      assertNull(registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio0 = RegistroDiCassav2Sig.Servizio.NEWORDINE;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza0 = RegistroDiCassav2Sig.AggiungiPizza.SI;
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza0 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 0, 0, 1);
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 1, 6, 6);
      assertEquals(RegistroDiCassav2Sig.Stati.PIZZASTANDARD_SELEZIONATA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.PIZZASTANDARD_SELEZIONATA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 1, 9, 6);
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(27, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegistroDiCassav2_ASM registroDiCassav2_ASM0 = new RegistroDiCassav2_ASM();
      assertNotNull(registroDiCassav2_ASM0);
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStato());
      assertNull(registroDiCassav2_ASM0.getAggiungiPizza());
      assertNull(registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertNull(registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio0 = RegistroDiCassav2Sig.Servizio.NEWORDINE;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza0 = RegistroDiCassav2Sig.AggiungiPizza.SI;
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza0 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 0, 0, 1);
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStato());
      
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza1 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza1, 1, 6, 6);
      assertEquals(RegistroDiCassav2Sig.Stati.ALTRAPIZZA_SELEZIONATA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.ALTRAPIZZA_SELEZIONATA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0);
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza1.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza0));
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza1, 1, 9, 6);
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStato());
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0);
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza1.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza0));
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 0, 1);
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStato());
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza1);
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza0.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza1));
      
      boolean boolean0 = registroDiCassav2_ASM0.isFinalState();
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStato());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RegistroDiCassav2_ASM registroDiCassav2_ASM0 = new RegistroDiCassav2_ASM();
      assertNotNull(registroDiCassav2_ASM0);
      assertNull(registroDiCassav2_ASM0.getAggiungiPizza());
      assertNull(registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertNull(registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStato());
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio0 = RegistroDiCassav2Sig.Servizio.NEWORDINE;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza0 = RegistroDiCassav2Sig.AggiungiPizza.SI;
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza0 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 0, 0, 1);
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza1 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza1, 1, 6, 6);
      assertEquals(RegistroDiCassav2Sig.Stati.ALTRAPIZZA_SELEZIONATA, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.Stati.ALTRAPIZZA_SELEZIONATA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.SI, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0);
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza1.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza0));
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio1 = RegistroDiCassav2Sig.Servizio.EXIT;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza1 = RegistroDiCassav2Sig.AggiungiPizza.NO;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza1, 1, 9, 6);
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.NO, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStato());
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0);
      assertNotSame(registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_AggiungiPizza0);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza1.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza0));
      assertFalse(registroDiCassav2Sig_AggiungiPizza1.equals((Object)registroDiCassav2Sig_AggiungiPizza0));
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza1, 2, 0, 1);
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.NO, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.OTHER, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Servizio.NEWORDINE, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStato());
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0);
      assertNotSame(registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_AggiungiPizza0);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza1.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza0));
      assertFalse(registroDiCassav2Sig_AggiungiPizza1.equals((Object)registroDiCassav2Sig_AggiungiPizza0));
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0, 1, 1, 6);
      assertEquals(RegistroDiCassav2Sig.Servizio.EXIT, registroDiCassav2_ASM0.getServizio());
      assertEquals(RegistroDiCassav2Sig.AggiungiPizza.NO, registroDiCassav2_ASM0.getAggiungiPizza());
      assertEquals(RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD, registroDiCassav2_ASM0.getSelezioneTipoDiPizza());
      assertEquals(54, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.CHIUSO, registroDiCassav2_ASM0.getStato());
      assertEquals(RegistroDiCassav2Sig.Stati.CHIUSO, registroDiCassav2_ASM0.getStatoCassa());
      assertNotSame(registroDiCassav2Sig_SelezioneTipoDiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza1);
      assertNotSame(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_Servizio0);
      assertNotSame(registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_AggiungiPizza0);
      assertFalse(registroDiCassav2Sig_SelezioneTipoDiPizza0.equals((Object)registroDiCassav2Sig_SelezioneTipoDiPizza1));
      assertFalse(registroDiCassav2Sig_Servizio1.equals((Object)registroDiCassav2Sig_Servizio0));
      assertFalse(registroDiCassav2Sig_AggiungiPizza1.equals((Object)registroDiCassav2Sig_AggiungiPizza0));
  }
}
