/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 11:59:29 GMT 2024
 */

package org.evoservice.atm3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ATM3v2_ESTest extends ATM3v2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.OTHER;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      aTM3v2_0.step();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertNotNull(boolean0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      
      aTM3v2_0.step();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      // Undeclared exception!
      try { 
        ATM3v2.MoneySizeSelection.valueOf("card1");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.MoneySizeSelection.card1
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card2");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.step();
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.OTHER;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      aTM3v2_0.step();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertNotNull(boolean0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
      
      // Undeclared exception!
      try { 
        ATM3v2.MoneySizeSelection.valueOf("card1");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.MoneySizeSelection.card1
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card2");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2 aTM3v2_1 = new ATM3v2();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotNull(aTM3v2_1);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      aTM3v2_1.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeOther(167);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      // Undeclared exception!
      try { 
        ATM3v2.Service.valueOf("7");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.Service.7
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertMoneySizeStandard(16);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertedPin(117);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeStandard(117);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedPin(0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_moneyLeft();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, int0);
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertFalse(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int1);
      
      // Undeclared exception!
      try { 
        ATM3v2.State.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.State.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.State[] aTM3v2_StateArray0 = ATM3v2.State.values();
      assertNotNull(aTM3v2_StateArray0);
      assertEquals(7, aTM3v2_StateArray0.length);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.OTHER;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.get_atmState();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int0 = aTM3v2_0.get_balance_card2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1652, int0);
      
      // Undeclared exception!
      try { 
        ATM3v2.Service.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.Service.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2 aTM3v2_1 = new ATM3v2();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotNull(aTM3v2_1);
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      
      int int0 = aTM3v2_1.get_balance_card1();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertEquals(3000, int0);
      
      int int1 = aTM3v2_0.get_balance_card2();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(int1 == int0);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(1652, int1);
      
      int int2 = aTM3v2_0.get_balance_card2();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(int2 == int0);
      assertTrue(int2 == int1);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(1652, int2);
      
      int int3 = aTM3v2_0.get_balance_card1();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(int3 == int1);
      assertFalse(int3 == int2);
      assertTrue(int3 == int0);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(3000, int3);
      
      ATM3v2 aTM3v2_2 = new ATM3v2();
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_0));
      assertNotNull(aTM3v2_2);
      assertEquals(1000, aTM3v2_2.get_moneyLeft());
      assertEquals(0, aTM3v2_2.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_2.get_atmState());
      
      Boolean boolean0 = aTM3v2_2.get_accessible_card3();
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_0));
      assertNotNull(boolean0);
      assertNotSame(aTM3v2_2, aTM3v2_1);
      assertNotSame(aTM3v2_2, aTM3v2_0);
      assertEquals(1000, aTM3v2_2.get_moneyLeft());
      assertEquals(0, aTM3v2_2.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_2.get_atmState());
      assertTrue(boolean0);
      
      aTM3v2_1.get_atmState();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_2));
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotSame(aTM3v2_1, aTM3v2_2);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      
      aTM3v2_2.set_insertMoneySizeOther(int3);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_2));
      assertFalse(int3 == int1);
      assertFalse(int3 == int2);
      assertTrue(int3 == int0);
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_0));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertNotSame(aTM3v2_0, aTM3v2_2);
      assertNotSame(aTM3v2_2, aTM3v2_1);
      assertNotSame(aTM3v2_2, aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(1000, aTM3v2_2.get_moneyLeft());
      assertEquals(0, aTM3v2_2.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_2.get_atmState());
      
      Boolean boolean1 = aTM3v2_2.get_accessible_card3();
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_2.equals((Object)aTM3v2_0));
      assertNotNull(boolean1);
      assertNotSame(aTM3v2_2, aTM3v2_1);
      assertNotSame(aTM3v2_2, aTM3v2_0);
      assertEquals(1000, aTM3v2_2.get_moneyLeft());
      assertEquals(0, aTM3v2_2.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_2.get_atmState());
      assertTrue(boolean1);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_2));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertNotSame(aTM3v2_0, aTM3v2_2);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int4 = aTM3v2_0.get_balance_card3();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_2));
      assertFalse(int4 == int2);
      assertFalse(int4 == int0);
      assertFalse(int4 == int3);
      assertFalse(int4 == int1);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertNotSame(aTM3v2_0, aTM3v2_2);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(548, int4);
      
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_2));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertNotSame(aTM3v2_0, aTM3v2_2);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_2));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertNotSame(aTM3v2_0, aTM3v2_2);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int5 = aTM3v2_1.get_numOfBalanceChecks();
      assertFalse(int5 == int3);
      assertFalse(int5 == int4);
      assertFalse(int5 == int2);
      assertFalse(int5 == int0);
      assertFalse(int5 == int1);
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_2));
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotSame(aTM3v2_1, aTM3v2_2);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertEquals(0, int5);
      
      ATM3v2.MoneySizeSelection[] aTM3v2_MoneySizeSelectionArray0 = ATM3v2.MoneySizeSelection.values();
      assertNotNull(aTM3v2_MoneySizeSelectionArray0);
      assertEquals(2, aTM3v2_MoneySizeSelectionArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertNotNull(aTM3v2_ServiceArray0);
      assertEquals(3, aTM3v2_ServiceArray0.length);
      
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -10
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(1);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.State[] aTM3v2_StateArray0 = ATM3v2.State.values();
      assertNotNull(aTM3v2_StateArray0);
      assertEquals(7, aTM3v2_StateArray0.length);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int0);
      
      aTM3v2_0.set_insertedPin((-3688));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertTrue(int1 == int0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int1);
      
      int int2 = aTM3v2_0.get_balance_card3();
      assertTrue(int2 == int1);
      assertTrue(int2 == int0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int2);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertNotNull(boolean0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedPin((-1424));
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1652, int0);
      
      int int1 = aTM3v2_0.get_balance_card1();
      assertFalse(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int1);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertNotNull(boolean0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      
      int int2 = aTM3v2_0.get_balance_card1();
      assertTrue(int2 == int1);
      assertFalse(int2 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int2);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      int int3 = aTM3v2_0.get_balance_card3();
      assertFalse(int3 == int1);
      assertFalse(int3 == int2);
      assertFalse(int3 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int3);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -10
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertNotNull(boolean0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.OTHER;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      aTM3v2_0.step();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertNotNull(boolean0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertNotNull(aTM3v2_ServiceArray0);
      assertEquals(3, aTM3v2_ServiceArray0.length);
      
      ATM3v2.Service[] aTM3v2_ServiceArray1 = ATM3v2.Service.values();
      assertFalse(aTM3v2_ServiceArray1.equals((Object)aTM3v2_ServiceArray0));
      assertNotNull(aTM3v2_ServiceArray1);
      assertNotSame(aTM3v2_ServiceArray1, aTM3v2_ServiceArray0);
      assertEquals(3, aTM3v2_ServiceArray1.length);
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertFalse(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int1);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection1 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection1);
      assertFalse(aTM3v2_MoneySizeSelection1.equals((Object)aTM3v2_MoneySizeSelection0));
      assertNotSame(aTM3v2_MoneySizeSelection1, aTM3v2_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card3();
      assertNotNull(boolean1);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean1);
      
      ATM3v2.MoneySizeSelection[] aTM3v2_MoneySizeSelectionArray0 = ATM3v2.MoneySizeSelection.values();
      assertNotNull(aTM3v2_MoneySizeSelectionArray0);
      assertEquals(2, aTM3v2_MoneySizeSelectionArray0.length);
      
      ATM3v2 aTM3v2_1 = new ATM3v2();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotNull(aTM3v2_1);
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      
      int int2 = aTM3v2_1.get_balance_card2();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertFalse(int2 == int1);
      assertFalse(int2 == int0);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertEquals(1652, int2);
      
      Integer integer0 = new Integer(3000);
      assertFalse(integer0.equals((Object)int2));
      assertTrue(integer0.equals((Object)int0));
      assertFalse(integer0.equals((Object)int1));
      assertNotNull(integer0);
      assertEquals(3000, (int)integer0);
      
      Boolean boolean2 = aTM3v2_1.get_accessible_card3();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertNotNull(boolean2);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertTrue(boolean2);
      
      aTM3v2_0.step();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertNotSame(aTM3v2_0, aTM3v2_1);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.CHOOSE, aTM3v2_0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertNotNull(boolean0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertNotNull(aTM3v2_ServiceArray0);
      assertEquals(3, aTM3v2_ServiceArray0.length);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard((-4177984));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -4177994
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertNotNull(boolean0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int0 = 1681;
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertNotNull(boolean0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      
      int int1 = aTM3v2_0.get_balance_card1();
      assertFalse(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(3000, int1);
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card3();
      assertNotNull(boolean1);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean1);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(1681);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1671
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int0 = aTM3v2_0.get_numOfBalanceChecks();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertNotNull(aTM3v2_0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.WITHDRAWAL;
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_Service1.equals((Object)aTM3v2_Service0));
      assertNotSame(aTM3v2_Service1, aTM3v2_Service0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertedCard("");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
