/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 24 17:42:05 GMT 2025
 */

package org.evoservice.cashpoint;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CashPointv2_ATG_ManualTest extends CashPointv2_ATG_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable {
      CashPointv2_ATG cashPointv2_ATG0 = new CashPointv2_ATG();
      assertNotNull(cashPointv2_ATG0);

      assertEquals(CashPointv2.TillState.WAITCARD, cashPointv2_ATG0.get_tillState_fromDomain_till1());
      assertEquals(2000,(int)cashPointv2_ATG0.get_balance_fromDomain_account1());

      cashPointv2_ATG0.step();

      assertEquals("abstract_card1", cashPointv2_ATG0.get_insertedCard_fromDomain_till1());
      assertEquals(CashPointv2.TillState.WAITPIN, cashPointv2_ATG0.get_tillState_fromDomain_till1());
      assertEquals(2000,(int)cashPointv2_ATG0.get_balance_fromDomain_account1());
      String string0 = cashPointv2_ATG0.get_cardLastUseDate_fromDomain_card1();
      assertEquals("abstract_monday", string0);
      assertTrue(cashPointv2_ATG0.get_legalCard_fromDomain_card1());
      assertEquals(0, (int)cashPointv2_ATG0.get_daily_withdraw_sum_fromDomain_card1());

      cashPointv2_ATG0.set_enteredPin_fromDomain_till1(1);
      cashPointv2_ATG0.set_abstract_currentDate("monday");
      cashPointv2_ATG0.set_amount_fromDomain_till1(500);

      cashPointv2_ATG0.step();

      assertEquals("abstract_card1", cashPointv2_ATG0.get_insertedCard_fromDomain_till1());
      assertEquals(CashPointv2.TillState.VALIDPIN, cashPointv2_ATG0.get_tillState_fromDomain_till1());
      assertEquals(1500,(int)cashPointv2_ATG0.get_balance_fromDomain_account1());
      assertEquals("abstract_monday", string0);
      assertTrue(cashPointv2_ATG0.get_legalCard_fromDomain_card1());
      assertEquals(-500, (int)cashPointv2_ATG0.get_daily_withdraw_sum_fromDomain_card1());

      cashPointv2_ATG0.step();

      cashPointv2_ATG0.set_amount_fromDomain_till1(500);

      assertEquals("abstract_card1", cashPointv2_ATG0.get_insertedCard_fromDomain_till1());
      assertEquals(CashPointv2.TillState.VALIDPIN, cashPointv2_ATG0.get_tillState_fromDomain_till1());
      assertEquals(1000,(int)cashPointv2_ATG0.get_balance_fromDomain_account1());
      assertEquals("abstract_monday", string0);
      assertTrue(cashPointv2_ATG0.get_legalCard_fromDomain_card1());
      assertEquals(-1000, (int)cashPointv2_ATG0.get_daily_withdraw_sum_fromDomain_card1());

  }

}
