/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 12 12:37:55 GMT 2024
 */

package org.evoservice.wrapper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ATM3v2_ASM_ESTest extends ATM3v2_ASM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertNotNull(aTM3v2_ASM0);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card1();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertTrue(boolean0);
      
      String string0 = "card3";
      int int0 = 3;
      aTM3v2_ASM0.set_insertedPin(int0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      
      aTM3v2_ASM0.set_insertedCard(string0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      
      aTM3v2_ASM0.step();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      
      int int1 = aTM3v2_ASM0.get_balance_card1();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertFalse(int1 == int0);
      assertEquals(3000, int1);
      
      Integer integer0 = new Integer(int1);
      assertFalse(int1 == int0);
      assertFalse(integer0.equals((Object)int0));
      assertTrue(integer0.equals((Object)int1));
      assertEquals(3000, (int)integer0);
      assertNotNull(integer0);
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection0 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.step();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.CHOOSE, aTM3v2_ASM0.get_atmState());
      
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.CHOOSE, aTM3v2_ASM0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1652, int0);
      
      int int1 = aTM3v2_ASM0.get_numOfBalanceChecks();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int1 == int0);
      assertEquals(0, int1);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card1();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertTrue(boolean0);
      
      aTM3v2_ASM0.set_insertMoneySizeOther(int1);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int1 == int0);
      
      String string0 = "card3";
      aTM3v2_ASM0.set_insertedCard(string0);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      aTM3v2_ASM0.step();
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      int int2 = aTM3v2_ASM0.get_balance_card1();
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int2 == int0);
      assertFalse(int2 == int1);
      assertEquals(3000, int2);
      
      int int3 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int3 == int1);
      assertTrue(int3 == int0);
      assertFalse(int3 == int2);
      assertEquals(1652, int3);
      
      int int4 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int4 == int2);
      assertTrue(int4 == int0);
      assertTrue(int4 == int3);
      assertFalse(int4 == int1);
      assertEquals(1652, int4);
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection0 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      aTM3v2_ASM0.step();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection1 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection1);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertSame(aTM3v2Sig_MoneySizeSelection1, aTM3v2Sig_MoneySizeSelection0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_numOfBalanceChecks();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(0, int0);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card1();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      
      int int1 = 0;
      aTM3v2_ASM0.set_insertMoneySizeOther(int1);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertTrue(int1 == int0);
      
      String string0 = "card3";
      aTM3v2_ASM0.set_insertedCard(string0);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      int int2 = aTM3v2_ASM0.get_balance_card1();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int2 == int0);
      assertFalse(int2 == int1);
      assertEquals(3000, int2);
      
      int int3 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int3 == int1);
      assertFalse(int3 == int2);
      assertFalse(int3 == int0);
      assertEquals(1652, int3);
      
      int int4 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertTrue(int4 == int3);
      assertFalse(int4 == int0);
      assertFalse(int4 == int1);
      assertFalse(int4 == int2);
      assertEquals(1652, int4);
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection0 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      aTM3v2_ASM0.step();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection1 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection1);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertSame(aTM3v2Sig_MoneySizeSelection1, aTM3v2Sig_MoneySizeSelection0);
      
      String string1 = "Y#x!x8Y";
      // Undeclared exception!
      try { 
        aTM3v2_ASM0.set_insertedCard(string1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      ATM3v2Sig.Service aTM3v2Sig_Service0 = ATM3v2Sig.Service.BALANCE;
      aTM3v2_ASM0.set_selectedService(aTM3v2Sig_Service0);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      int int0 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1652, int0);
      
      aTM3v2_ASM0.get_atmState();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      
      int int1 = aTM3v2_ASM0.get_numOfBalanceChecks();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int1 == int0);
      assertEquals(0, int1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection0 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      ATM3v2Sig.Service aTM3v2Sig_Service0 = ATM3v2Sig.Service.WITHDRAWAL;
      int int0 = 200;
      aTM3v2_ASM0.set_insertMoneySizeStandard(int0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      int int1 = aTM3v2_ASM0.get_balance_card3();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int1 == int0);
      assertEquals(548, int1);
      
      aTM3v2_ASM0.set_selectedService(aTM3v2Sig_Service0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card1();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertTrue(boolean0);
      
      int int2 = aTM3v2_ASM0.get_moneyLeft();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int2 == int1);
      assertFalse(int2 == int0);
      assertEquals(1000, int2);
      
      boolean boolean1 = aTM3v2_ASM0.get_accessible_card2();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
      
      int int3 = aTM3v2_ASM0.get_balance_card3();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int3 == int2);
      assertFalse(int3 == int0);
      assertTrue(int3 == int1);
      assertEquals(548, int3);
      
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      int int4 = aTM3v2_ASM0.get_balance_card3();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int4 == int2);
      assertFalse(int4 == int0);
      assertTrue(int4 == int3);
      assertTrue(int4 == int1);
      assertEquals(548, int4);
      
      aTM3v2_ASM0.set_insertMoneySizeOther(int2);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int2 == int4);
      assertFalse(int2 == int3);
      assertFalse(int2 == int1);
      assertFalse(int2 == int0);
      
      int int5 = 16;
      aTM3v2_ASM0.set_insertMoneySizeOther(int5);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertFalse(int5 == int0);
      assertFalse(int5 == int1);
      assertFalse(int5 == int4);
      assertFalse(int5 == int3);
      assertFalse(int5 == int2);
      
      String string0 = "PVm*H!v";
      // Undeclared exception!
      try { 
        aTM3v2_ASM0.set_insertedCard(string0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      ATM3v2Sig.Service aTM3v2Sig_Service0 = ATM3v2Sig.Service.WITHDRAWAL;
      aTM3v2_ASM0.set_selectedService(aTM3v2Sig_Service0);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      ATM3v2Sig.MoneySizeSelection aTM3v2Sig_MoneySizeSelection0 = ATM3v2Sig.MoneySizeSelection.OTHER;
      aTM3v2_ASM0.set_standardOrOther(aTM3v2Sig_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_moneyLeft();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = 355;
      aTM3v2_ASM0.set_insertedPin(int0);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertNotNull(aTM3v2_ASM0);
      
      ATM3v2Sig.NumCard aTM3v2Sig_NumCard0 = aTM3v2_ASM0.get_currCard();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertNull(aTM3v2Sig_NumCard0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card3();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertTrue(boolean0);
      
      // Undeclared exception!
      try { 
        aTM3v2_ASM0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.wrapper.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1652, int0);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card1();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertTrue(boolean0);
      
      aTM3v2_ASM0.get_atmState();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      aTM3v2_ASM0.set_insertMoneySizeOther(int0);
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertNotNull(aTM3v2_ASM0);
      
      aTM3v2_ASM0.get_atmState();
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      
      int int0 = 1262;
      // Undeclared exception!
      try { 
        aTM3v2_ASM0.set_insertMoneySizeStandard(int0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1252
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_balance_card3();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(548, int0);
      
      int int1 = aTM3v2_ASM0.get_balance_card1();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int1 == int0);
      assertEquals(3000, int1);
      
      int int2 = aTM3v2_ASM0.get_balance_card2();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertFalse(int2 == int1);
      assertFalse(int2 == int0);
      assertEquals(1652, int2);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = aTM3v2_ASM0.get_balance_card1();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(3000, int0);
      
      boolean boolean0 = aTM3v2_ASM0.get_accessible_card2();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      int int0 = (-1408);
      aTM3v2_ASM0.set_insertMoneySizeOther(int0);
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_ASM0);
      
      String string0 = "";
      // Undeclared exception!
      try { 
        aTM3v2_ASM0.set_insertedCard(string0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ATM3v2_ASM aTM3v2_ASM0 = new ATM3v2_ASM();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertNotNull(aTM3v2_ASM0);
      
      String string0 = "card3";
      aTM3v2_ASM0.set_insertedCard(string0);
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      
      aTM3v2_ASM0.step();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
      assertEquals(ATM3v2Sig.State.AWAITPIN, aTM3v2_ASM0.get_atmState());
      
      aTM3v2_ASM0.step();
      assertEquals(0, aTM3v2_ASM0.get_numOfBalanceChecks());
      assertEquals(ATM3v2Sig.State.AWAITCARD, aTM3v2_ASM0.get_atmState());
      assertEquals(1000, aTM3v2_ASM0.get_moneyLeft());
  }
}
