/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 29 14:44:13 GMT 2024
 */

package org.evoservice.RegistroDiCassa;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evoservice.RegistroDiCassa.RegistroDiCassav2Sig;
import org.evoservice.RegistroDiCassa.RegistroDiCassav2_ASM;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegistroDiCassav2_ASM_ESTest extends RegistroDiCassav2_ASM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegistroDiCassav2_ASM registroDiCassav2_ASM0 = new RegistroDiCassav2_ASM();
      assertNotNull(registroDiCassav2_ASM0);
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio0 = RegistroDiCassav2Sig.Servizio.EXIT;
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza0 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza0 = RegistroDiCassav2Sig.AggiungiPizza.SI;
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio1 = RegistroDiCassav2Sig.Servizio.NEWORDINE;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 2, 2);
      assertNotSame(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_Servizio0);
      assertFalse(registroDiCassav2Sig_Servizio1.equals((Object)registroDiCassav2Sig_Servizio0));
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 2, 10);
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.PIZZASTANDARD_SELEZIONATA, registroDiCassav2_ASM0.getStatoCassa());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 10, 10);
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 3, 2);
      assertNotSame(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_Servizio0);
      assertFalse(registroDiCassav2Sig_Servizio1.equals((Object)registroDiCassav2Sig_Servizio0));
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      
      boolean boolean0 = registroDiCassav2_ASM0.isFinalState();
      assertFalse(boolean0);
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegistroDiCassav2_ASM registroDiCassav2_ASM0 = new RegistroDiCassav2_ASM();
      assertNotNull(registroDiCassav2_ASM0);
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio0 = RegistroDiCassav2Sig.Servizio.EXIT;
      RegistroDiCassav2Sig.SelezioneTipoDiPizza registroDiCassav2Sig_SelezioneTipoDiPizza0 = RegistroDiCassav2Sig.SelezioneTipoDiPizza.STANDARD;
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza0 = RegistroDiCassav2Sig.AggiungiPizza.SI;
      RegistroDiCassav2Sig.Servizio registroDiCassav2Sig_Servizio1 = RegistroDiCassav2Sig.Servizio.NEWORDINE;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 2, 2);
      assertNotSame(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_Servizio0);
      assertFalse(registroDiCassav2Sig_Servizio1.equals((Object)registroDiCassav2Sig_Servizio0));
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_TIPO_DI_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 2, 10);
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertEquals(RegistroDiCassav2Sig.Stati.PIZZASTANDARD_SELEZIONATA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(0, registroDiCassav2_ASM0.getTotale());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 10, 10);
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertEquals(RegistroDiCassav2Sig.Stati.SCEGLI_SE_AGGIUNGERE_PIZZA, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
      
      RegistroDiCassav2Sig.AggiungiPizza registroDiCassav2Sig_AggiungiPizza1 = RegistroDiCassav2Sig.AggiungiPizza.NO;
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 3, 2);
      assertNotSame(registroDiCassav2Sig_Servizio1, registroDiCassav2Sig_Servizio0);
      assertNotSame(registroDiCassav2Sig_AggiungiPizza1, registroDiCassav2Sig_AggiungiPizza0);
      assertFalse(registroDiCassav2Sig_Servizio1.equals((Object)registroDiCassav2Sig_Servizio0));
      assertFalse(registroDiCassav2Sig_AggiungiPizza1.equals((Object)registroDiCassav2Sig_AggiungiPizza0));
      assertEquals(RegistroDiCassav2Sig.Stati.ATTENDI_ORDINAZIONI, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
      
      registroDiCassav2_ASM0.step(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_SelezioneTipoDiPizza0, 2, 10, 2);
      assertNotSame(registroDiCassav2Sig_Servizio0, registroDiCassav2Sig_Servizio1);
      assertNotSame(registroDiCassav2Sig_AggiungiPizza0, registroDiCassav2Sig_AggiungiPizza1);
      assertFalse(registroDiCassav2Sig_Servizio0.equals((Object)registroDiCassav2Sig_Servizio1));
      assertFalse(registroDiCassav2Sig_AggiungiPizza0.equals((Object)registroDiCassav2Sig_AggiungiPizza1));
      assertEquals(RegistroDiCassav2Sig.Stati.CHIUSO, registroDiCassav2_ASM0.getStatoCassa());
      assertEquals(50, registroDiCassav2_ASM0.getTotale());
  }
}
