/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 12:42:28 GMT 2024
 */

package org.evoservice.atm3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ATM3v2_ESTest extends ATM3v2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      ATM3v2 aTM3v2_1 = new ATM3v2();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertNotNull(aTM3v2_1);
      
      Boolean boolean1 = aTM3v2_1.get_accessible_card1();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      
      aTM3v2_1.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertNotSame(aTM3v2_1, aTM3v2_0);
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertTrue(int1 == int0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int1);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.WITHDRAWAL;
      aTM3v2_1.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertFalse(aTM3v2_Service1.equals((Object)aTM3v2_Service0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertNotSame(aTM3v2_1, aTM3v2_0);
      assertNotSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.set_insertMoneySizeOther(1034);
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotSame(aTM3v2_0, aTM3v2_1);
      
      aTM3v2_0.step();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertNotSame(aTM3v2_0, aTM3v2_1);
      
      aTM3v2_1.set_insertMoneySizeOther(0);
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertNotSame(aTM3v2_1, aTM3v2_0);
      
      boolean boolean2 = aTM3v2_1.isFinalState();
      assertFalse(aTM3v2_1.equals((Object)aTM3v2_0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_1.get_atmState());
      assertFalse(aTM3v2_1.isFinalState());
      assertEquals(0, aTM3v2_1.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_1.get_moneyLeft());
      assertFalse(boolean2);
      assertNotSame(aTM3v2_1, aTM3v2_0);
      
      aTM3v2_0.step();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertEquals(ATM3v2.State.CHOOSE, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertNotSame(aTM3v2_0, aTM3v2_1);
      
      Integer integer0 = new Integer(0);
      assertFalse(integer0.equals((Object)int0));
      assertFalse(integer0.equals((Object)int1));
      assertEquals(0, (int)integer0);
      assertNotNull(integer0);
      
      Boolean boolean3 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertFalse(boolean3.equals((Object)boolean2));
      assertEquals(ATM3v2.State.CHOOSE, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertTrue(boolean3);
      assertNotNull(boolean3);
      assertNotSame(aTM3v2_0, aTM3v2_1);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertEquals(3, aTM3v2_ServiceArray0.length);
      assertNotNull(aTM3v2_ServiceArray0);
      
      boolean boolean4 = aTM3v2_0.isFinalState();
      assertFalse(aTM3v2_0.equals((Object)aTM3v2_1));
      assertTrue(boolean4 == boolean2);
      assertEquals(ATM3v2.State.CHOOSE, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertFalse(boolean4);
      assertNotSame(aTM3v2_0, aTM3v2_1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertedCard("card1");
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.step();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      boolean boolean1 = aTM3v2_0.isFinalState();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(boolean1);
      
      aTM3v2_0.step();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean2 = aTM3v2_0.get_accessible_card2();
      assertFalse(boolean2.equals((Object)boolean1));
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean2);
      assertNotNull(boolean2);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertEquals(3, aTM3v2_ServiceArray0.length);
      assertNotNull(aTM3v2_ServiceArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(2031);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      Boolean boolean0 = Boolean.TRUE;
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      aTM3v2_0.step();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertTrue(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(548, int1);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      boolean boolean2 = aTM3v2_0.isFinalState();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(boolean2);
      
      aTM3v2_0.step();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(548);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 538
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertedCard("card1");
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertTrue(int1 == int0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(548, int1);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      boolean boolean1 = aTM3v2_0.isFinalState();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(boolean1);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(548);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 538
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.WITHDRAWAL;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_Service1.equals((Object)aTM3v2_Service0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertNotSame(aTM3v2_Service1, aTM3v2_Service0);
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertTrue(int1 == int0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(548, int1);
      
      ATM3v2.Service aTM3v2_Service2 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service2);
      assertFalse(aTM3v2_Service2.equals((Object)aTM3v2_Service0));
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertNotSame(aTM3v2_Service2, aTM3v2_Service0);
      assertSame(aTM3v2_Service2, aTM3v2_Service1);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      
      boolean boolean1 = aTM3v2_0.isFinalState();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertFalse(boolean1);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(548);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 538
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      boolean boolean0 = aTM3v2_0.isFinalState();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_numOfBalanceChecks();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(0, int0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      int int1 = aTM3v2_0.get_balance_card2();
      assertFalse(int1 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1652, int1);
      
      ATM3v2.State[] aTM3v2_StateArray0 = ATM3v2.State.values();
      assertEquals(7, aTM3v2_StateArray0.length);
      assertNotNull(aTM3v2_StateArray0);
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      
      int int2 = aTM3v2_0.get_balance_card2();
      assertTrue(int2 == int1);
      assertFalse(int2 == int0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1652, int2);
      
      aTM3v2_0.set_insertMoneySizeOther(711);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.OTHER;
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertedCard("@RO1R9s=Y-}/");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_numOfBalanceChecks();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(0, int0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_numOfBalanceChecks();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, int0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      
      int int1 = aTM3v2_0.get_balance_card2();
      assertFalse(int1 == int0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1652, int1);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_moneyLeft();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, int0);
      
      int int1 = aTM3v2_0.get_numOfBalanceChecks();
      assertFalse(int1 == int0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, int1);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_balance_card2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(1652, int0);
      
      // Undeclared exception!
      try { 
        ATM3v2.MoneySizeSelection.valueOf("N");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.MoneySizeSelection.N
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ATM3v2.State[] aTM3v2_StateArray0 = ATM3v2.State.values();
      assertEquals(7, aTM3v2_StateArray0.length);
      assertNotNull(aTM3v2_StateArray0);
      
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_balance_card2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1652, int0);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      
      aTM3v2_0.set_insertMoneySizeStandard(107);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      
      int int1 = aTM3v2_0.get_balance_card2();
      assertTrue(int1 == int0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1652, int1);
      
      int int2 = aTM3v2_0.get_moneyLeft();
      assertFalse(int2 == int1);
      assertFalse(int2 == int0);
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, int2);
      
      String string0 = "C}No7sn]RJ#&TX-";
      // Undeclared exception!
      try { 
        ATM3v2.MoneySizeSelection.valueOf("C}No7sn]RJ#&TX-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.evoservice.atm3.ATM3v2.MoneySizeSelection.C}No7sn]RJ#&TX-
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(3000, int0);
      
      aTM3v2_0.get_atmState();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      String string0 = "org.evoservice.atm3.ATM3v2$Fun0";
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(3000);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2990
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.WITHDRAWAL;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertFalse(aTM3v2_Service1.equals((Object)aTM3v2_Service0));
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.get_atmState();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard((-236));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -246
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeOther(0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertMoneySizeStandard(175);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.set_insertedCard("card1");
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int0 = aTM3v2_0.get_balance_card3();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.EXIT;
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card1();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int1 = aTM3v2_0.get_balance_card3();
      assertTrue(int1 == int0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(548, int1);
      
      ATM3v2.Service aTM3v2_Service1 = ATM3v2.Service.EXIT;
      aTM3v2_0.set_selectedService(aTM3v2_Service1);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertSame(aTM3v2_Service1, aTM3v2_Service0);
      
      aTM3v2_0.set_insertMoneySizeOther(548);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      aTM3v2_0.step();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      aTM3v2_0.set_insertMoneySizeOther(175);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      boolean boolean2 = aTM3v2_0.isFinalState();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITPIN, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(boolean2);
      
      aTM3v2_0.step();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      int int2 = new Integer(0);
      assertFalse(int2 == int0);
      assertFalse(int2 == int1);
      assertEquals(0, int2);
      
      Boolean boolean3 = aTM3v2_0.get_accessible_card2();
      assertFalse(boolean3.equals((Object)boolean2));
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean3);
      assertNotNull(boolean3);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertEquals(3, aTM3v2_ServiceArray0.length);
      assertNotNull(aTM3v2_ServiceArray0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(3000, int0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertMoneySizeOther(139);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.WITHDRAWAL;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      
      int int0 = aTM3v2_0.get_moneyLeft();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(1000, int0);
      
      int int1 = aTM3v2_0.get_numOfBalanceChecks();
      assertFalse(int1 == int0);
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, int1);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card2();
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      int int0 = aTM3v2_0.get_balance_card1();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(3000, int0);
      
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      boolean boolean1 = aTM3v2_0.isFinalState();
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertFalse(boolean1);
      
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertEquals(3, aTM3v2_ServiceArray0.length);
      assertNotNull(aTM3v2_ServiceArray0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertNotNull(aTM3v2_0);
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      boolean boolean1 = aTM3v2_0.isFinalState();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ATM3v2.Service[] aTM3v2_ServiceArray0 = ATM3v2.Service.values();
      assertEquals(3, aTM3v2_ServiceArray0.length);
      assertNotNull(aTM3v2_ServiceArray0);
      
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertedPin(0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      
      // Undeclared exception!
      try { 
        aTM3v2_0.set_insertMoneySizeStandard(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -10
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertNotNull(aTM3v2_0);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ATM3v2 aTM3v2_0 = new ATM3v2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertNotNull(aTM3v2_0);
      
      aTM3v2_0.set_insertedPin((-1556));
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean0 = aTM3v2_0.get_accessible_card3();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean0);
      assertNotNull(boolean0);
      
      int int0 = aTM3v2_0.get_balance_card1();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertEquals(3000, int0);
      
      ATM3v2.Service aTM3v2_Service0 = ATM3v2.Service.BALANCE;
      aTM3v2_0.set_selectedService(aTM3v2_Service0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean1 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean1);
      assertNotNull(boolean1);
      
      Boolean boolean2 = aTM3v2_0.get_accessible_card1();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean2);
      assertNotNull(boolean2);
      
      ATM3v2.MoneySizeSelection aTM3v2_MoneySizeSelection0 = ATM3v2.MoneySizeSelection.STANDARD;
      aTM3v2_0.set_standardOrOther(aTM3v2_MoneySizeSelection0);
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      
      Boolean boolean3 = aTM3v2_0.get_accessible_card2();
      assertFalse(aTM3v2_0.isFinalState());
      assertEquals(1000, aTM3v2_0.get_moneyLeft());
      assertEquals(0, aTM3v2_0.get_numOfBalanceChecks());
      assertEquals(ATM3v2.State.AWAITCARD, aTM3v2_0.get_atmState());
      assertTrue(boolean3);
      assertNotNull(boolean3);
      
      // Undeclared exception!
      try { 
        aTM3v2_0.step();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evoservice.atm3.ATM3v2", e);
      }
  }
}
